### ISSUE TITLE
轻松地给 Google Play 换区 | Love4Taylor's Blog

### ISSUE THREAD

**Issue by Love4Taylor** [Love4Taylor/Blog-Comment#10]
https://love4taylor.me/easily-change-google-play-country.html 

 一个不爱写文章的伪 Geek/Linuxer 的博客(算是吧23333)

**Comment by hakuame** [comment]
有些地方不太清楚能解释一下么？
1. 填写信息后需要给新的地址添加支付方法么，还是单纯地添加新地址就OK了？
2. 梯子=VPN？清空Google Play的数据重新登陆了是清空数据后重新打开Google Play的意思，还是注销账号再次登录？

**Comment by Love4Taylor** [comment]
> @hakuame
> 有些地方不太清楚能解释一下么？
> 1. 填写信息后需要给新的地址添加支付方法么，还是单纯地添加新地址就OK了？
> 2. 梯子=VPN？清空Google Play的数据重新登陆了是清空数据后重新打开Google Play的意思，还是注销账号再次登录？

1. 支付方式随意 我当时没绑. 重点是"付款资料"的地区.
2. 清空 Google Play 数据目的和注销又没差别 只是更简单粗暴点.

**Comment by hakuame** [comment]
> @Love4Taylor
> > @hakuame
> > 有些地方不太清楚能解释一下么？
> > 1. 填写信息后需要给新的地址添加支付方法么，还是单纯地添加新地址就OK了？
> > 2. 梯子=VPN？清空Google Play的数据重新登陆了是清空数据后重新打开Google Play的意思，还是注销账号再次登录？
> 
> 1. 支付方式随意 我当时没绑. 重点是"付款资料"的地区.
> 2. 清空 Google Play 数据目的和注销又没差别 只是更简单粗暴点.

谢谢dalao。你的情况跟我很相似，我试了很多网上的方法都不行。现在手机VPN在挂着，希望能转到日区吧。
