### ISSUE TITLE
我的 Nexus 6 以及 Pure Nexus(多图预警) | Love4Taylor's Blog

### ISSUE THREAD

**Issue by Love4Taylor** [Love4Taylor/Blog-Comment#3]
https://love4taylor.me/my-nexus6-purenexus.html 

 一个不爱写文章的伪 Geek/Linuxer 的博客(算是吧23333)

**Comment by xiaohaogong** [comment]
pure nexus rom 支持 f2fs吗？另外，您自己nexus6用的是f2fs吗

**Comment by Love4Taylor** [comment]
> @xiaohaogong
> pure nexus rom 支持 f2fs吗？另外，您自己nexus6用的是f2fs吗

可能有些问题 我用 PN+F2FS 的时候会出现某些应用的兼容问题 例如拍的照片在图库里是灰色的... 目前不是 F2FS 不过也不推荐再用这个了 因为和 SDCardFS 以及文件加密冲突

**Comment by xiaohaogong** [comment]
> @Love4Taylor
> > @xiaohaogong
> > pure nexus rom 支持 f2fs吗？另外，您自己nexus6用的是f2fs吗
> 
> 可能有些问题 我用 PN+F2FS 的时候会出现某些应用的兼容问题 例如拍的照片在图库里是灰色的... 目前不是 F2FS 不过也不推荐再用这个了 因为和 SDCardFS 以及文件加密冲突


> @Love4Taylor
> > @xiaohaogong
> > pure nexus rom 支持 f2fs吗？另外，您自己nexus6用的是f2fs吗
> 
> 可能有些问题 我用 PN+F2FS 的时候会出现某些应用的兼容问题 例如拍的照片在图库里是灰色的... 目前不是 F2FS 不过也不推荐再用这个了 因为和 SDCardFS 以及文件加密冲突

sigma kernel 可用于exT4文件系统吗

**Comment by Love4Taylor** [comment]
> @xiaohaogong
> > @Love4Taylor
> > > @xiaohaogong
> > > pure nexus rom 支持 f2fs吗？另外，您自己nexus6用的是f2fs吗
> > 
> > 可能有些问题 我用 PN+F2FS 的时候会出现某些应用的兼容问题 例如拍的照片在图库里是灰色的... 目前不是 F2FS 不过也不推荐再用这个了 因为和 SDCardFS 以及文件加密冲突
> 
> 
> > @Love4Taylor
> > > @xiaohaogong
> > > pure nexus rom 支持 f2fs吗？另外，您自己nexus6用的是f2fs吗
> > 
> > 可能有些问题 我用 PN+F2FS 的时候会出现某些应用的兼容问题 例如拍的照片在图库里是灰色的... 目前不是 F2FS 不过也不推荐再用这个了 因为和 SDCardFS 以及文件加密冲突
> 
> sigma kernel 可用于exT4文件系统吗

当然可以啊
