### ISSUE TITLE
Kryptonite 一款 SSH 密钥管理/认证工具 | Love4Taylor's Blog

### ISSUE THREAD

**Issue by Love4Taylor** [Love4Taylor/Blog-Comment#9]
https://love4taylor.me/kryptonite-review.html 

 一个不爱写文章的伪 Geek/Linuxer 的博客(算是吧23333)

**Comment by ivmm** [comment]
这家要是倒了咋办

**Comment by Love4Taylor** [comment]
> @ivmm
> 这家要是倒了咋办

确实有这方面的隐患 如果倒了我就很不要脸希望他完全开源吧 233333
